<?php
declare(strict_types = 1);

namespace Infrastructure\Service;

use Domain\Service\HashingService;
use Domain\ValueObject\Password;
use Domain\ValueObject\HashedPassword;

/**
 * Class BcryptHashingService
 *
 * Creates a new password hash using a strong one-way hashing algorithm
 *
 * The salt option has been deprecated as of PHP 7.0.0. It is now
 * preferred to simply use the salt that is generated by default.
 *
 * @author Vasil Dakov <vasildakov@gmail.com>
 */
class BcryptHashingService implements HashingService
{
    /**
     * Algorithmic cost that should be used
     */
    const COST = 8;

    /**
     * @param  \Domain\ValueObject\Password          $password
     * @return \Domain\ValueObject\HashedPassword
     */
    public function __invoke(Password $password): HashedPassword
    {
        $hash = \password_hash( (string) $password, PASSWORD_BCRYPT, [self::COST]);

        return new HashedPassword($hash);
    }
}
